### ISSUE TITLE
Error while runing the exemple

### ISSUE THREAD

**Issue by pigeonvictor** [adamhenson/mongobackup#2]
Hi !

I'm trying to run the simple exemple provided in the readme, but this error is thrown. Any idea ?
```
[00:07:49] Using gulpfile ~\WebstormProjects\MaPUI\gulpfile.js
[00:07:49] Starting 'mongodump'...
[00:07:49] Finished 'mongodump' after 3.19 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn mongodump ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

Thank you.

**Comment by pigeonvictor** [comment]
Ok I'm just dumb, doesn't work on windows....

**Comment by adamhenson** [comment]
No problem. Sorry about that @pigeonvictor. I should put that at the top of the documentation.

**Comment by pigeonvictor** [comment]
Yeah or juste highlight or capitalize the part about windows :)
